workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH =~ /^manticore-.*$/
    - if: $TEST || $WHAT

# to skip ci add [ci skip] or [skip ci] in commit message in any capitalization

stages:
  - docs
  - init
  - main
  - hooks

docs_deploy_check:
  stage: docs
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH =~ /^manticore-.*$/
  image: registry.gitlab.com/manticoresearch/doc/autodeploy:latest
  cache: {}
  services:
    - docker:18.09.7-dind
  script:
    - cp "$CI_PROJECT_DIR/gitlab-ci-main.yml" main-conf.yml
    - cp "$CI_PROJECT_DIR/dist/gitlab-release.yml" release-conf.yml
    - DOC_DIR="manual/"
    - VAR_SET=" 1"
    - res=$(echo $(git diff-tree --no-commit-id --name-only -r -m "$CI_COMMIT_SHA" | grep -v "^$DOC_DIR"))
    - if [ "$res" == "" ]; then echo "  DOCS_COMMIT_ONLY:$VAR_SET" >> main-conf.yml; fi  
    - if [ "$res" == "" ] && [ -z "$FORCE_BUILDS" ]; then echo "  DOCS_COMMIT_ONLY:$VAR_SET" >> release-conf.yml; fi
    - res=$(echo $(git diff-tree --no-commit-id --name-only -r -m "$CI_COMMIT_SHA" | grep "^$DOC_DIR"))
    - if ! [ "$res" == "" ]; then sh /Deploy/autoupdate.sh k8s; fi
  artifacts:
    paths:
      - main-conf.yml
      - release-conf.yml
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2   
    COMMIT_DIR: manual
    RELEASE_FILENAME: latest_release_version


init:
  stage: init
  when: always
  script:
    - if [ ! -f "main-conf.yml" ]; then cp  "$CI_PROJECT_DIR/gitlab-ci-main.yml" main-conf.yml; fi
    - if [ ! -f "release-conf.yml" ]; then cp "$CI_PROJECT_DIR/dist/gitlab-release.yml" release-conf.yml; fi
  artifacts:
    paths:
      - main-conf.yml
      - release-conf.yml
    
main:
  stage: main
  variables:
    WHAT: $WHAT
    REPO_NAME: $REPO_NAME
    DOCKER_HUB_BUILD_URL: $DOCKER_HUB_BUILD_URL
  when: always
  trigger:
    include:
      - artifact: main-conf.yml
        job: init
    strategy: depend


deploy_hook:
  stage: hooks
  variables:
    WHAT: $WHAT
    REPO_NAME: $REPO_NAME
    DOCKER_HUB_BUILD_URL: $DOCKER_HUB_BUILD_URL
  when: always
  trigger:
    include:
      - artifact: release-conf.yml
        job: init
    strategy: depend