workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $TEST || $WHAT

stages:
  - mirroring
  - routines
  - build
  - publish

include: '/dist/gitlab-release.yml'

pages:
  stage: routines
  tags:
    - docker
  image: registry.gitlab.com/manticoresearch/dev/manticoredocs:latest
  script:
    - cd docs
    - make html
    - cd -
    - mkdir .public
    - cp -r docs/build/html/* .public
    - mv .public public
  artifacts:
    paths:
    - public
  rules:
    - if: $TEST==null && $CI_COMMIT_BRANCH == "master"
  cache: {}

job_mirror:
  stage: mirroring
  tags:
    - dev-host
  rules:
    - if: $TEST==null && $CI_COMMIT_BRANCH == "master"
  script:
    - ~/gitsync.sh
  cache: {}

simple_tests:
  stage: routines
  rules:
    - if: $TEST==null && $WHAT==null && $CI_COMMIT_TITLE !~ /^noci .*$/i && $CI_COMMIT_TITLE !~ /^nocilinux .*$/i
    - if: $TEST =~ /simple/
  tags:
    - specdocker
  dependencies: []
  image: registry.gitlab.com/manticoresearch/dev/ubertests:latest
  variables:
    CTEST_BUILD_CONFIGURATION: "Debug"
    CACHEB: "../cache"
    DIAGNOSTIC: 1 # let's set it by default forever
  script:
    - ctest -V -S misc/ctest/gltest.cmake
  after_script:
    - cd build && mkdir xml_simple_tests
    - cp -r Testing/2*/*.xml xml_simple_tests
  artifacts:
    paths:
    - build/xml_simple_tests
    - build/test/test_*/report.txt
    - build/test/error*.txt
    - build/test/searchd.log
    expire_in: 12 hrs
    when: always
  cache:
    key: ubuntu_bionic
    paths:
      - cache/*-src
      - cache/galera*64/libgalera*
      - cache/galera*64/galera-targets.cmake
      - cache/icu*64/*icu*
      - cache/re2*64/*re2*
      - cache/stemmer*64/*stemmer*

release_tests:
  stage: routines
  rules:
    - if: $TEST==null && $WHAT==null && $CI_COMMIT_TITLE !~ /^noci .*$/i && $CI_COMMIT_TITLE !~ /^nocilinux .*$/i
    - if: $TEST =~ /release/
  tags:
    - specdocker
  dependencies: []
  image: registry.gitlab.com/manticoresearch/dev/ubertests:latest
  variables:
    CTEST_BUILD_CONFIGURATION: "RelWithDebInfo"
    CACHEB: "../cache"
  script:
    - ctest -V -S misc/ctest/gltest.cmake
  after_script:
    - cd build && mkdir xml_release_tests
    - cp -r Testing/2*/*.xml xml_release_tests
  artifacts:
    paths:
    - build/xml_release_tests
    - build/test/test_*/report.txt
    - build/test/error*.txt
    - build/test/searchd.log
    expire_in: 12 hrs
    when: always
  cache:
    key: ubuntu_bionic
    paths:
      - cache/*-src
      - cache/galera*64/libgalera*
      - cache/galera*64/galera-targets.cmake
      - cache/icu*64/*icu*
      - cache/re2*64/*re2*
      - cache/stemmer*64/*stemmer*
  retry: 1

win_tests:
  stage: routines
  rules:
    - if: $TEST==null && $WHAT==null && $CI_COMMIT_TITLE !~ /^noci .*$/i && $CI_COMMIT_TITLE !~ /^nociwindows .*$/i
    - if: $TEST =~ /windows/
  tags:
    - windev19
    - build
  dependencies: []
  variables:
    LIBS_BUNDLE: "x:/bundle"
    CACHEB: "x:/cache"
    OPENSSL_ROOT_DIR: "x:/bundle/openssl-x64"
    COPY_DLL: "x:/bundle/dll"
    WIN_TEST_CI: "1"
    CTEST_BUILD_CONFIGURATION: "Debug"
    CTEST_CMAKE_GENERATOR : "Visual Studio 16 2019"
    DIAGNOSTIC: 1 # let's set it by default forever
  script:
    - 'net use x: \\\\VBOXSRV\\shared'
#    - export PATH='/cygdrive/x/bundle/openssl-x64:/cygdrive/x/bundle/Expat-1.95.8/Libs:/cygdrive/x/bundle/libiconv-1.9.1/bin:/cygdrive/x/bundle/mysql/bin:'$PATH
    - ctest -V -S misc/ctest/gltest.cmake -DCTEST_SOURCE_DIRECTORY='C:/cygwin64/home/manticore/builds/manticoresearch/dev/' -C Debug
  after_script:
    - cd build && mkdir xml_win_tests
    - cp -r Testing/2*/*.xml xml_win_tests
  artifacts:
    paths:
      - build/xml_win_tests
      - build/test/test_*/report.txt
      - build/test/error*.txt
      - build/test/searchd.log
    expire_in: 12 hrs
    when: always
  cache: {}
  retry: 1

build_mac:
  stage: routines
  rules:
    - if: $TEST==null && $WHAT==null && $CI_COMMIT_TITLE !~ /^noci .*$/i && $CI_COMMIT_TITLE !~ /^nocimacos .*$/i
    - if: $TEST =~ /macos/
  tags:
    - mac
    - build
  dependencies: []
  variables:
    CTEST_BUILD_CONFIGURATION: "Debug"
    CACHEB: "../cache"
    OPENSSL_ROOT_DIR: "/usr/local/opt/openssl"
    CTEST_CMAKE_GENERATOR: "Unix Makefiles"
    DIAGNOSTIC: 1 # let's set it by default forever
  script:
    - mkdir build && cd build
    - ctest -VV -S ../misc/ctest/justbuild.cmake -DCTEST_SOURCE_DIRECTORY=..
  after_script:
    - cd build && mkdir xml_build_mac
    - cp -r Testing/2*/*.xml xml_build_mac
  artifacts:
    paths:
      - build/xml_build_mac
      - build/CMakeFiles/CMake*.log
    expire_in: 12 hrs
    when: always
  cache:
    key: darwin
    paths:
      - cache/*-src
      - cache/galera*64/libgalera*
      - cache/galera*64/galera-targets.cmake
      - cache/icu*64/*icu*
      - cache/re2*64/*re2*
      - cache/stemmer*64/*stemmer*
      - cache/boost*64

build_bsd:
  stage: routines
  rules:
    - if: $TEST==null && $WHAT==null && $CI_COMMIT_TITLE !~ /^noci .*$/i && $CI_COMMIT_TITLE !~ /^nocifreebsd .*$/i
    - if: $TEST =~ /freebsd/
  tags:
    - freebsd
    - build
  dependencies: []
  variables:
    CTEST_BUILD_CONFIGURATION: "Debug"
    CACHEB: "../cache"
    CTEST_CMAKE_GENERATOR: "Unix Makefiles"
    DIAGNOSTIC: 1 # let's set it by default forever
  script:
    - mkdir build && cd build
    - ctest -VV -S ../misc/ctest/justbuild.cmake -DCTEST_SOURCE_DIRECTORY=..
  after_script:
    - cd build && mkdir xml_build_bsd
    - cp -r Testing/2*/*.xml xml_build_bsd
  artifacts:
    paths:
      - build/xml_build_bsd
      - build/CMakeFiles/CMake*.log
    expire_in: 12 hrs
    when: always
  cache:
    key: freebsd
    paths:
      - cache/*-src
      - cache/galera*64/libgalera*
      - cache/galera*64/galera-targets.cmake
      - cache/icu*64/*icu*
      - cache/re2*64/*re2*
      - cache/stemmer*64/*stemmer*

push_results:
  stage: publish
  rules:
    - if: $WHAT==null && $CI_COMMIT_TITLE !~ /^noci .*$/i
      when: always
  tags:
    - specdocker
  image: registry.gitlab.com/manticoresearch/dev/ubertests:latest
  dependencies:
    - simple_tests
    - release_tests
    - win_tests
    - build_mac
    - build_bsd
  variables:
    GIT_STRATEGY: fetch
  script:
    - ctest -S misc/ctest/upload.cmake
  artifacts:
    reports:
      junit: build/junit_*.xml
  cache: {}
  environment:
    name: ${CI_COMMIT_REF_NAME}
    url: http://$CDASH_URL/CDash/public/index.php?project=Manticoresearch&filtercount=1&field1=revision&compare1=63&value1=$CI_COMMIT_SHA
  retry: 1
  allow_failure: true
