stages:
  - build
  - test_plain
  - test_rt
  - docs

job_mirror:
  stage: build
  only:
    - master
  script:
    - ~/gitsync.sh
  allow_failure: true

job_build:
  stage: build
  script:
    - mkdir build && cd build
    - cmake ..
    - make -j8

job_test_plain:
  stage: test_plain
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make -j8
    - ctest -LE RT || ctest --rerun-failed || EXIT_CODE=$?
    - exit ${EXIT_CODE}
  artifacts:
    when: always
    paths:
      - build/test/test_*/report.txt
      - build/test/error*.txt
      - build/test/searchd.log

job_test_rt:
  stage: test_rt
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make -j8
    - ctest -L RT || ctest --rerun-failed || EXIT_CODE=$?
    - exit ${EXIT_CODE}
  artifacts:
    when: always
    paths:
      - build/test/test_*/report.txt
      - build/test/error*.txt
      - build/test/searchd.log

pages:
  stage: docs
  tags:
    - docs
    - docker
  image: registry.gitlab.com/manticoresearch/dev/manticoredocs:latest
  script:
    - cd docs
    - make html
    - cd -
    - mkdir .public
    - cp -r docs/build/html/* .public
    - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
