stages:
  - unittests

simple_tests:
  stage: unittests
  tags:
    - ubuntu
    - specdocker
  image: registry.gitlab.com/manticoresearch/dev/ubertests:latest
  script:
    - ctest -V -S /work/gltest.cmake

disabled_id64_tests:
  stage: unittests
  tags:
    - ubuntu
    - specdocker
  image: registry.gitlab.com/manticoresearch/dev/ubertests:latest
  script:
    - ctest -V -DDISABLE_ID64=1 -S /work/gltest.cmake

checkdocs:
  stage: unittests
  tags:
    - docs
    - docker
  image: registry.gitlab.com/manticoresearch/dev/manticoredocs:latest
  script:
    - cd docs
    - make html
    - cd ..
