stages:
  - build
  - test_plain
  - test_rt
  - docs

job_mirror:
  stage: build
  only:
    - master
  script:
    - ~/gitsync.sh
  allow_failure: true

job_build:
  stage: build
  script:
    - rm -R build/ || /bin/true
    - mkdir build && cd build
    - cmake ..
    - make -j8

job_test_plain:
  stage: test_plain
  script:
    - rm -R build/ || /bin/true
    - mkdir build && cd build
    - cmake ..
    - make -j8
    - rm result_plain.zip || /bin/true
    - ctest -E rt_ || ctest --rerun-failed -E rt_ || EXIT_CODE=$?
    - exit ${EXIT_CODE}
  artifacts:
    when: always
    paths:
      - build/test/test_*/report.txt
      - build/test/error.txt
  retry: 2

job_test_rt:
  stage: test_rt
  script:
    - rm -R build/ || /bin/true
    - mkdir build && cd build
    - cmake ..
    - make -j8
    - rm result_rt.zip || /bin/true
    - ctest -R rt_ || ctest --rerun-failed -R rt_ || EXIT_CODE=$?
    - exit ${EXIT_CODE}
  artifacts:
    when: always
    paths:
      - build/test/test_*/report.txt
      - build/test/error.txt
  retry: 2

pages:
  stage: docs
  tags:
    - docs
    - docker
  image: registry.gitlab.com/manticoresearch/dev/manticoredocs:latest
  script:
    - cd docs
    - make html
    - cd -
    - mkdir .public
    - cp -r docs/build/html/* .public
    - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
